# Generated by Django 5.0.2 on 2024-03-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='books')),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
